# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'cronometro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Each', '~> 1.2'

  target 'cronometroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cronometroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
